# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

dist: trusty
sudo: required

language: python
python: 3.6

env:
  - VS_GIT_VERSION=R38

before_install:
  - sudo add-apt-repository ppa:djcj/vapoursynth -y
  - sudo apt-get update -q
  - sudo apt-get install -y vapoursynth
  - pip install Cython
  - pip install https://github.com/vapoursynth/vapoursynth/archive/${VS_GIT_VERSION}.tar.gz

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install .

# command to run tests, e.g. python setup.py test
script: python -m unittest discover tests

before_deploy:
  - pip install -r requirements_dev.txt
  - cd docs && make html

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    repo: stuxcrystal/yuuno.encode.moe
    target_branch: master
    fqdn: yuuno.encode.moe
    on:
      branch: master
      repo: stuxcrystal/yuuno

  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    target_branch: gh-pages
    fqdn: yuuno-devel.encode.moe
    on:
      branch: development
      repo: stuxcrystal/yuuno

  - provider: pypi
    distributions: sdist --format=zip bdist_wheel
    user: stuxcrystal
    password:
      secure: !!binary |
        RExJZnNyQlplbE9lWjNmUER2a0tOQmhZVkl5Q1VJbXpaYUZsdjRmQjB4KysrZTl5V0JUMGhPY3pk
        NHB0WkQrZ1pDWW1sYWlwK1JhTlZtYVYrdGxISHlRMURKeUpUcTJ2NE8wbUdsZVlhYmFEckNDZWtI
        RS84RnFuN1JhSTk3aUdwVGJ6V2RrVmdRL1JHaGdZV0g1QlpUUVVjRmh3b1ZDOVBzZndSb0pKM05V
        cGpQT0JRUE9wMVRSV3Y4UjlpMlRaRHBWRElBRjZkTnkwRVR3RzZSeTNheXVlUEdyVzFYdTNUVmhy
        bXpWc1EzQ3ViM3Y0NFg4cWJhK2NXSnVCUDVlaEFRTUNxbFJ4aWU1bWZSRkdxdFJoWHJiOUhwbEFI
        N2hPdVF1bmlWQ251ZEFjL3lVd2Ird3BsY0dmcG9TV2FqWjNaeHVvamFlaXJnOE03SFYveVlETjEv
        ZGpaWkpuY2tUa1BsZGxOUUh6Y1U0eDRJZmNzM3Y3SkkvOHNBWCtpZHd4eFB1L2ttYWFsck9oVnR3
        Q1RxRDhUZGlvRTZlVHZ0UjIzNUoveHhROURKYjNwTWhRZXEyKzIrdC9veUxOZjJTdllQYlhmRXRl
        VFZDRGVaZ3Ird3BtaDk2aFJKaDdZTHl6OWxQWUxWZzF5L3lzR3FJaXMrVnVrZGdYY3M1RFJ2alpm
        OHErbVIza0c3ZzJuend0dFg5dnMranV6UDllVFpWTEc4U0lubjVyUXhBUjFDaTNIMVRJN3dEM2NY
        aE91Z1BoQUdSZlB6ek53RE1nR1dnb3NRWm1PUUlvbkxIdDY2Q2cxTElrUkRzU0lIRy9JdzRjMkhx
        NGFaMjRGczJZZXVTQ2tMYndWNVlIbnhBTTF4QnU1eVVnU2VodVRCeXRSNjVlMG51K21pWHpMN289
    on:
      tags: true
      repo: stuxcrystal/yuuno
